services:
  - type: web
    plan: free
    runtime: node
    autoDeploy: false
    name: hanno-dashboard
    buildCommand: npm install --prod=false; npm run schema; npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: DATABASE_URL
        sync: false
