services:
  - type: web
    name: hanno-blog
    runtime: node
    plan: free
    buildCommand: pnpm install --prod=false; pnpm schema; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
